pipeline {
    agent any

    stages {
        stage('Pull code from branch main') {
            steps {
                git branch: 'main', url: 'https://github.com/Fyefee/Software-Tool-Final.git'
            }
        }
        stage('Download dependency') {
            steps {
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }
        stage('Run unit test') {
            steps {
                dir('frontend') {
                    sh 'npm run unit-test'
                }
            }
        }
        stage('Build') {
            steps {
                dir('frontend') {
                    sh 'npm build'
                }
            }
        }
    }
}